#cloud-config
package_update: true

write_files:
- owner: azureuser:azureuser
- path: /home/azureuser/docker-compose.yml
  content: |
    version: "3.7"
    services:
      shinyproxy:
        image: wandersnet/shinyproxy
        container_name: shinyproxy
        restart: on-failure
        ports:
          - "80:8080"
        networks:
          - shinyproxy-net          
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        # add volume "shinyvolume" in azure webapp congiguration/path mappings
        # - shinyvolume:/var/run/docker.sock:/var/run/docker.sock
        # - /shinyproxy-logs/server:/log
        # - /shinyproxy-logs/container:/container-logs
        # - /shinyproxy:/opt/shinyproxy
        depends_on:
          - shinydemo
      shinydemo:
        image: openanalytics/shinyproxy-demo
    networks: 
      shinyproxy-net:
        name: shinyproxy-net

# Install docker and docker-compose and run docker-compose
runcmd:
    - [ sh, -c, 'curl -sSL https://get.docker.com/ | sh' ]
    - [ sh, -c, 'sudo curl -L https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep "tag_name" | cut -d \" -f4)/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose' ]
    - [ sh, -c, 'sudo chmod +x /usr/local/bin/docker-compose' ]
    - cd /home/azureuser
    - 'docker-compose up -d'

# Add default auto created user to docker group
system_info:
    default_user:
        groups: [docker]