apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinyproxy
spec:
  selector:
    matchLabels:
      run: shinyproxy
  replicas: 1
  template:
    metadata:
      labels:
        run: shinyproxy
    spec:
      containers:
      - name: shinyproxy
        image: wandersnet/shinyproxy
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
      - name: kube-proxy-sidecar
        image: wandersnet/kube-proxy-sidecar
        ports:
        - containerPort: 8001
